FROM ubuntu:18.04

ENV TZ=Europe/Madrid
ENV DEBIAN_FRONTEND=noninteractive

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install software-properties-common ca-certificates apt-transport-https apt-get install systemd -y
RUN add-apt-repository ppa:ondrej/php

ADD script.sh /tmp/script.sh
RUN chmod +x /tmp/script.sh
RUN /tmp/script.sh