FROM nextcloud

ENV NEXTCLOUD_ADMIN_USER="administrador" \
    NEXTCLOUD_ADMIN_PASSWORD="s;0MC1}c|Vj4@rAgRFs8"
ENV MYSQL_DATABASE="bd-nextcloud" \
    MYSQL_USER="usuario-nextcloud" \
    MYSQL_PASSWORD="7qYFwDb+ptC[bqnBA0[]" \
    MYSQL_HOST="172.16.0.3"

EXPOSE 80
EXPOSE 443
