---
    apiVersion: v1
    kind: Secret
    metadata:
      name: config-nextcloud
    type: Opaque
    data:
      # User admin nextcloud
      nextcloud-username: YWRtaW5pc3RyYWRvcg==
      nextcloud-password: czswTUMxfWN8Vmo0QHJBZ1JGczg=
      # Database (MYSQL)
      mysql-database: YmQtbmV4dGNsb3Vk
      mysql-user: dXN1YXJpby1uZXh0Y2xvdWQ=
      mysql-password: N3FZRndEYitwdENbYnFuQkEwW10=
      mysql-host: bXlzcWwtc2VydmljZTozMzA2
      # Trust domain in Nextcloud
      nextcloud-domain: bmV4dC5sdWRpYmEub3Jn
      # Directory to store the data
      nextcloud-dir-data: L3Zhci93d3cvaHRtbC9kYXRh
---
    apiVersion: v1
    kind: Secret
    metadata:
      name: config-mysql
    type: Opaque
    data:
        mysql-root-password: dFtXPWE7RzF4cHJOeElvUDdZdis=
        mysql-name-database: YmQtbmV4dGNsb3Vk
        mysql-user: dXN1YXJpby1uZXh0Y2xvdWQ=
        mysql-user-password: N3FZRndEYitwdENbYnFuQkEwW10=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: redxlus/nextcloud-img
        ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
        env:
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: nextcloud-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: nextcloud-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: mysql-password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: mysql-host
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: nextcloud-domain
        - name: NEXTCLOUD_DATA_DIR
          valueFrom:
            secretKeyRef:
                name: config-nextcloud
                key: nextcloud-dir-data
      initContainers:
        - name: init-check
          image: busybox
          command: ["sh", "-c", "echo 'until nc mysql-service 3306' > script.sh && \
                    echo 'do' >> script.sh && \
                    echo 'sleep 3' >> script.sh && \
                    echo 'done' >> script.sh && \
                    sh script.sh"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: redxlus/mysql-img
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - name: mysql
    targetPort: 3306
    port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  ports:
  - name: https
    containerPort: 443
    protocol: TCP
  - name: http
    containerPort: 80
    protocol: TCP
  selector:
    app: nextcloud
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: next.ludiba.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud-service
          servicePort: http
    
