---
apiVersion: v1
kind: Secret
metadata:
  name: config-nextcloud
type: Opaque
data:
  nextcloud-username: "YWRtaW4="
  nextcloud-password: "Y2hhbmdlbWU="
  nextcloud-dominio: "bmV4dC5sdWRpYmEub3Jn"
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-nextcloud
  labels:
    app: nextcloud
    tipo: deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: "nextcloud:16.0.8-apache"
        command: ["/bin/sh"]
        args: ["-c", "while true; do a2enmod ssl && /etc/init.d/apache2 restart; sleep infinity;done"]
        env:
        - name: SQLITE_DATABASE
          value: "nextcloud"
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: config-nextcloud
              key: nextcloud-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-nextcloud
              key: nextcloud-password
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            secretKeyRef:
              name: config-nextcloud
              key: nextcloud-dominio
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: pvc
          mountPath: /var/www/
          subPath: root
        - name: pvc
          mountPath: /var/www/html
          subPath: html
        - name: pvc
          mountPath: /var/www/html/data
          subPath: data
        - name: pvc
          mountPath: /var/www/html/config
          subPath: config
        - name: pvc
          mountPath: /var/www/html/custom_apps
          subPath: custom_apps
        - name: pvc
          mountPath: /var/www/tmp
          subPath: tmp
        - name: pvc
          mountPath: /var/www/html/themes
          subPath: themes
      volumes:
      - name: pvc
        persistentVolumeClaim:
         claimName: cualquier-nombre-persistent-volume-claim
      # Will mount configuration files as www-data (id: 33) for nextcloud
      securityContext:
        fsGroup: 33
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cualquier-nombre-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
        
---
kind: Service
apiVersion: v1
metadata:
  name: loadbalancer-nextcloud
spec:
  type: LoadBalancer
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http