name: Twitter Bot - Docker Image CI
on:
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image of HOSTING --> BOTS --> Twitter
      run: |
        docker build --file HOSTING/BOTS/Twitter/dockerfile --tag twitter-bot . 
        docker tag twitter-bot:latest ${{ secrets.USER_DOCKER }}/twitter-bot:m-$(date +%B)
    - name: Docker login
      run: docker login --username='${{ secrets.USER_DOCKER }}' --password=${{ secrets.PASS_DOCKER }}
    - name: Docker push image of HOSTING --> BOTS --> Twitter
      run: docker push ${{ secrets.USER_DOCKER }}/twitter-bot:m-$(date +%B)
