name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image of HOSTING --> GAMES --> Minecraft
      run: docker build --file HOSTING/GAMES/Minecraft/dockerfile --tag $usuario/minecraft-server:$(date +%s) .
      env:
       usuario: ${{ secrets.USER_DOCKER }}
       contrasena: ${{ secrets.PASS_DOCKER }}
    - name: Docker login
      env:
       usuario: ${{ secrets.USER_DOCKER }}
       contrasena: ${{ secrets.PASS_DOCKER }}
      run: docker login --username $usuario --password $contrasena
    - name: Docker push image of HOSTING --> GAMES --> Minecraft
      run: docker push $usuario/minecraft-server:$(date +%s)
      env:
       usuario: ${{ secrets.USER_DOCKER }}
       contrasena: ${{ secrets.PASS_DOCKER }}
