name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Build the Docker image of HOSTING --> GAMES --> Minecraft
    #  run: docker build --file HOSTING/GAMES/Minecraft/dockerfile --tag my-image-name:$(date +%s) .
    - name: Upload Docker image of HOSTING --> GAMES --> Minecraft
      env: # Or as an environment variable
       usuario: ${{ secrets.USER_DOCKER }}
      run: echo $usuario
      # run: docker login --username=yourhubusername --email=youremail@company.com

