name: Instagram Bot - Docker Image CI
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install buildx to multi-arch docker images
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Docker login
      run: docker login --username='${{ secrets.USER_DOCKER }}' --password=${{ secrets.PASS_DOCKER }}
    - name: Build the Docker image of HOSTING --> BOTS --> Instagram & push
      run: |
        docker buildx build --push \
          --tag ${{ secrets.USER_DOCKER }}/instagram-bot:$(date +%Y-%B) \
          --file 'HOSTING/BOTS/Instagram/dockerfile' \
          --platform linux/amd64,linux/arm/v7
