name: Minecraft Server - Docker Image CI 
on:
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image of HOSTING --> GAMES --> Minecraft
      run: |
        docker build --file HOSTING/GAMES/Minecraft/dockerfile --tag minecraft . 
        docker tag minecraft:latest ${{ secrets.USER_DOCKER }}/minecraft-server:m-$(date +%Y-%B)
    - name: Docker login
      run: docker login --username='${{ secrets.USER_DOCKER }}' --password=${{ secrets.PASS_DOCKER }}
    - name: Docker push image of HOSTING --> GAMES --> Minecraft
      run: docker push ${{ secrets.USER_DOCKER }}/minecraft-server:m-$(date +%Y-%B)
