name: Instragram Bot - Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image of HOSTING --> BOTS --> Instagram
      run: |
        docker build --file HOSTING/BOTS/Twitter/dockerfile --tag instagram-bot . 
        docker tag instagram-bot:latest ${{ secrets.USER_DOCKER }}/instagram-bot:m-$(date +%Y-%B)
    - name: Docker login
      run: docker login --username='${{ secrets.USER_DOCKER }}' --password=${{ secrets.PASS_DOCKER }}
    - name: Docker push image of HOSTING --> BOTS --> Instagram
      run: docker push ${{ secrets.USER_DOCKER }}/instagram-bot:m-$(date +%Y-%B)
