name: Instagram Bot - Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker build and push image of HOSTING --> BOTS --> Instagram
      run: |
        docker build --file HOSTING/BOTS/Instagram/Dockerfile \
                                            --tag ${{ secrets.DOCKERHUB_USERNAME }}/instagram-bot:$(date +%Y-%B) \
                                            --tag ${{ secrets.DOCKERHUB_USERNAME }}/instagram-bot:latest .
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/instagram-bot --all-tags
