name: Nextcloud & MySQL - Docker Image CI
on:
  schedule:
    - cron:  '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker build and push image of HOSTING --> STORAGE --> Nextcloud --> mysql
      run: |
        docker build --file HOSTING/STORAGE/Nextcloud/mysql/Dockerfile \
                                            --tag ${{ secrets.DOCKERHUB_USERNAME }}/mysql-img:$(date +%Y-%B) \
                                            --tag ${{ secrets.DOCKERHUB_USERNAME }}/mysql-img:latest .
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mysql-img --all-tags
    - name: Docker build and push image of HOSTING --> STORAGE --> Nextcloud
      run: |
        docker build --file HOSTING/ACCESS/Dockerfile \
                                            --tag ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-img:$(date +%Y-%B) \
                                            --tag ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-img:latest .
        docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-img --all-tags
