name: Minecraft Server - Docker Image CI 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image of HOSTING --> GAMES --> Minecraft
      run: |
        docker build --file HOSTING/GAMES/Minecraft/dockerfile --tag minecraft . 
        docker tag minecraft redxlus/minecraft-server:m-$(date +%b)
    - name: Docker login
      run: docker login --username='redxlus' --password=${{ secrets.PASS_DOCKER }}
    - name: Docker push image of HOSTING --> GAMES --> Minecraft
      run: docker push redxlus/minecraft-server:m-$(date +%b)
